import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Foundations',
      link: { type: 'doc', id: 'module1/what-is-ai-native-development' },
      items: [
        'module1/what-is-ai-native-development',
        'module1/core-principles-of-ai-native',
        'module1/the-role-of-llms-in-software-engineering',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      link: { type: 'doc', id: 'module2/introduction-to-prompt-engineering' },
      items: [
        'module2/introduction-to-prompt-engineering',
        'module2/advanced-prompting-techniques',
        'module2/fine-tuning-vs-retrieval-augmented-generation-rag',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain',
      link: { type: 'doc', id: 'module3/the-rise-of-ai-agents' },
      items: [
        'module3/the-rise-of-ai-agents',
        'module3/designing-and-building-an-agentic-system',
        'module3/tools-and-frameworks-for-agent-development',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Robotics',
      link: { type: 'doc', id: 'module4/introduction-to-ros-2' },
      items: [
        'module4/introduction-to-ros-2',
        'module4/simulating-robots-with-gazebo-and-isaac-sim',
        'module4/vision-language-action-vla-models-in-practice',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-basics', // Generates sidebar items from docs/tutorial-basics
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-extras', // Generates sidebar items from docs/tutorial-extras
    },
    'sources',
  ],
};

export default sidebars;